import { Character, Item, Upgrade, Weapon } from './types';

export const ENEMY_DICTIONARY = [
  { id: 'bat', name: '吸血蝙蝠', desc: '最基础的敌人，主要靠数量取胜。', attack: '只会向你移动，造成近战伤害。', spawn: '游戏开始时即出现。', color: '#ff5555' },
  { id: 'fairy', name: '妖精', desc: '体型较小，移动速度极快。', attack: '快速向你移动，造成近战伤害。', spawn: '第1分钟后开始出现。', color: '#55ff55' },
  { id: 'ghost', name: '怨灵', desc: '体型庞大，血量极高的坦克型敌人。', attack: '缓慢向你移动，造成近战伤害。', spawn: '第2分钟后开始出现。', color: '#5555ff' },
  { id: 'shooter', name: '魔法使', desc: '掌握了魔法的敌人，会在远处停下。', attack: '向你发射菱形的魔法弹幕。', spawn: '第3分钟后开始出现。', color: '#ffff55' },
  { id: 'elite_shooter', name: '精英魔法使', desc: '更加强大的魔法使，血量较高。', attack: '一次性发射3发扇形的菱形弹幕。', spawn: '第6分钟后开始出现。', color: '#ffaa00' },
  { id: 'remilia', name: '蕾米莉亚', desc: '红魔馆的主人，吸血鬼领主。', attack: '阶段一：全方位星形弹幕。阶段二：精准的菱形散弹射击。', spawn: '第3分钟出现的BOSS。', color: '#ff0000', isBoss: true },
  { id: 'yukari', name: '八云紫', desc: '操纵境界的妖怪，神出鬼没。', attack: '阶段一：螺旋状圆形弹幕。阶段二：传送到玩家附近并向八个方向发射弹幕。', spawn: '第6分钟出现的BOSS。', color: '#aa00ff', isBoss: true },
  { id: 'okina', name: '摩多罗隐岐奈', desc: '后户之神，弹幕极具压迫感。', attack: '阶段一：快速扫射的星形激光弹幕。阶段二：在玩家周围召唤不断缩小的圆形弹幕阵。', spawn: '第9分钟出现的BOSS。', color: '#ffaa00', isBoss: true }
];

export const CHARACTERS: Character[] = [
  {
    id: 'reimu',
    name: '博丽灵梦',
    description: '乐园的巫女。属性均衡。',
    color: '#ff0000',
    baseStats: {
      maxHp: 100,
      speed: 150,
      damage: 1,
      area: 1,
      cooldown: 1,
      magnet: 60,
      armor: 0,
      luck: 1,
      amount: 0,
    },
    startingWeapon: 'amulet',
  },
  {
    id: 'marisa',
    name: '雾雨魔理沙',
    description: '普通的魔法使。高移速和伤害，低血量。',
    color: '#ffff00',
    baseStats: {
      maxHp: 70,
      speed: 180,
      damage: 1.2,
      area: 1,
      cooldown: 0.9,
      magnet: 80,
      armor: 0,
      luck: 1,
      amount: 0,
    },
    startingWeapon: 'magic_missile',
  },
  {
    id: 'cirno',
    name: '琪露诺',
    description: '冰之妖精。额外投射物，低伤害。',
    color: '#00ccff',
    baseStats: {
      maxHp: 90,
      speed: 160,
      damage: 0.8,
      area: 1,
      cooldown: 1,
      magnet: 50,
      armor: 0,
      luck: 1.2,
      amount: 1,
    },
    startingWeapon: 'icicle',
  },
  {
    id: 'youmu',
    name: '魂魄妖梦',
    description: '半人半灵的庭师。高移速和护甲，近战特化。',
    color: '#00ff88',
    baseStats: {
      maxHp: 120,
      speed: 170,
      damage: 1.1,
      area: 1.2,
      cooldown: 1,
      magnet: 50,
      armor: 2,
      luck: 1,
      amount: 0,
    },
    startingWeapon: 'sword',
  },
];

export const WEAPONS: Record<string, Weapon> = {
  amulet: {
    id: 'amulet',
    name: '博丽灵符',
    description: '发射追踪附近敌人的灵符。',
    maxLevel: 8,
    color: '#ffaaaa',
    type: 'projectile',
    baseStats: {
      damage: 10,
      cooldown: 1.5,
      area: 20,
      speed: 300,
      amount: 1,
      duration: 3,
      piercing: 1,
    },
    levelUpgrades: {
      2: { amount: 1, description: '发射 1 个额外的投射物。' },
      3: { damage: 5, cooldown: -0.2, description: '基础伤害增加 5。冷却时间减少。' },
      4: { amount: 1, description: '发射 1 个额外的投射物。' },
      5: { damage: 5, area: 5, description: '基础伤害增加 5。范围增加。' },
      6: { amount: 1, description: '发射 1 个额外的投射物。' },
      7: { piercing: 1, description: '穿透 1 个额外的敌人。' },
      8: { damage: 10, amount: 1, description: '伤害增加 10。发射 1 个额外的投射物。' },
    },
  },
  magic_missile: {
    id: 'magic_missile',
    name: '魔法飞弹',
    description: '向你面朝的方向发射快速的飞弹。',
    maxLevel: 8,
    color: '#ffffaa',
    type: 'projectile',
    baseStats: {
      damage: 15,
      cooldown: 1.0,
      area: 15,
      speed: 500,
      amount: 1,
      duration: 2,
      piercing: 1,
    },
    levelUpgrades: {
      2: { amount: 1, description: '发射 1 个额外的投射物。' },
      3: { cooldown: -0.2, description: '冷却时间减少。' },
      4: { amount: 1, piercing: 1, description: '发射 1 个额外的投射物。穿透 1 个额外的敌人。' },
      5: { damage: 10, description: '基础伤害增加 10。' },
      6: { amount: 1, description: '发射 1 个额外的投射物。' },
      7: { piercing: 2, description: '穿透 2 个额外的敌人。' },
      8: { damage: 15, amount: 1, description: '伤害增加 15。发射 1 个额外的投射物。' },
    },
  },
  icicle: {
    id: 'icicle',
    name: '冰柱坠落',
    description: '向随机方向发射冰柱。',
    maxLevel: 8,
    color: '#aaffff',
    type: 'projectile',
    baseStats: {
      damage: 8,
      cooldown: 0.8,
      area: 15,
      speed: 250,
      amount: 3,
      duration: 2,
      piercing: 1,
    },
    levelUpgrades: {
      2: { amount: 2, description: '发射 2 个额外的投射物。' },
      3: { damage: 4, description: '基础伤害增加 4。' },
      4: { amount: 2, description: '发射 2 个额外的投射物。' },
      5: { cooldown: -0.2, description: '冷却时间减少。' },
      6: { amount: 2, description: '发射 2 个额外的投射物。' },
      7: { piercing: 1, description: '穿透 1 个额外的敌人。' },
      8: { damage: 8, amount: 3, description: '伤害增加 8。发射 3 个额外的投射物。' },
    },
  },
  sword: {
    id: 'sword',
    name: '楼观剑',
    description: '在角色前方进行近战挥砍。',
    maxLevel: 8,
    color: '#ffffff',
    type: 'melee',
    baseStats: {
      damage: 25,
      cooldown: 1.2,
      area: 60,
      speed: 0,
      amount: 1,
      duration: 0.2,
      piercing: 999,
    },
    levelUpgrades: {
      2: { area: 15, description: '攻击范围增加。' },
      3: { damage: 10, description: '基础伤害增加 10。' },
      4: { cooldown: -0.2, description: '冷却时间减少。' },
      5: { area: 15, description: '攻击范围增加。' },
      6: { damage: 15, description: '基础伤害增加 15。' },
      7: { cooldown: -0.2, description: '冷却时间减少。' },
      8: { damage: 20, area: 20, description: '伤害和范围大幅增加。' },
    },
  },
  barrier: {
    id: 'barrier',
    name: '阴阳结界',
    description: '伤害靠近的敌人。',
    maxLevel: 8,
    color: '#ff00ff',
    type: 'aura',
    baseStats: {
      damage: 5,
      cooldown: 0.5,
      area: 80,
      speed: 0,
      amount: 1,
      duration: 999,
      piercing: 999,
    },
    levelUpgrades: {
      2: { area: 10, description: '结界范围增加。' },
      3: { damage: 3, description: '基础伤害增加 3。' },
      4: { area: 10, description: '结界范围增加。' },
      5: { cooldown: -0.1, description: '攻击频率增加。' },
      6: { damage: 4, description: '基础伤害增加 4。' },
      7: { area: 15, description: '结界范围增加。' },
      8: { damage: 8, cooldown: -0.1, description: '伤害增加，攻击频率增加。' },
    },
  },
  knife: {
    id: 'knife',
    name: '银飞刀',
    description: '向前方发射多把飞刀。',
    maxLevel: 8,
    color: '#dddddd',
    type: 'projectile',
    baseStats: {
      damage: 12,
      cooldown: 0.8,
      area: 10,
      speed: 600,
      amount: 3,
      duration: 1.5,
      piercing: 1,
    },
    levelUpgrades: {
      2: { amount: 1, description: '发射 1 把额外的飞刀。' },
      3: { damage: 4, description: '基础伤害增加 4。' },
      4: { amount: 1, piercing: 1, description: '发射 1 把额外的飞刀。穿透 1 个额外的敌人。' },
      5: { cooldown: -0.1, description: '冷却时间减少。' },
      6: { amount: 1, description: '发射 1 把额外的飞刀。' },
      7: { piercing: 1, description: '穿透 1 个额外的敌人。' },
      8: { damage: 8, amount: 2, description: '伤害增加 8。发射 2 把额外的飞刀。' },
    },
  },
  master_spark: {
    id: 'master_spark',
    name: '极限火花',
    description: '发射巨大的激光扫射前方。',
    maxLevel: 8,
    color: '#ffff55',
    type: 'projectile',
    baseStats: {
      damage: 40,
      cooldown: 4.0,
      area: 60,
      speed: 800,
      amount: 1,
      duration: 2,
      piercing: 999,
    },
    levelUpgrades: {
      2: { damage: 10, description: '基础伤害增加 10。' },
      3: { cooldown: -0.5, description: '冷却时间减少。' },
      4: { area: 20, description: '激光范围增加。' },
      5: { damage: 20, description: '基础伤害增加 20。' },
      6: { cooldown: -0.5, description: '冷却时间减少。' },
      7: { area: 20, description: '激光范围增加。' },
      8: { damage: 30, cooldown: -0.5, description: '伤害大幅增加，冷却时间减少。' },
    },
  },
  bounce_orb: {
    id: 'bounce_orb',
    name: '阴阳玉(弹跳)',
    description: '发射在敌人之间弹跳的阴阳玉。',
    maxLevel: 8,
    color: '#ff55ff',
    type: 'projectile',
    baseStats: {
      damage: 15,
      cooldown: 1.5,
      area: 15,
      speed: 400,
      amount: 1,
      duration: 4,
      piercing: 3,
    },
    levelUpgrades: {
      2: { piercing: 2, description: '弹跳次数增加 2。' },
      3: { damage: 5, description: '基础伤害增加 5。' },
      4: { amount: 1, description: '发射 1 个额外的阴阳玉。' },
      5: { piercing: 2, description: '弹跳次数增加 2。' },
      6: { damage: 10, description: '基础伤害增加 10。' },
      7: { cooldown: -0.3, description: '冷却时间减少。' },
      8: { amount: 1, piercing: 3, description: '发射 1 个额外的阴阳玉。弹跳次数增加 3。' },
    },
  },
};

export const ITEMS: Record<string, Item> = {
  spinach: {
    id: 'spinach',
    name: '力量道具',
    description: '增加 10% 伤害。',
    maxLevel: 5,
    color: '#ff5555',
    statModifiers: {
      1: { damage: 0.1, description: '增加 10% 伤害。' },
      2: { damage: 0.1, description: '增加 10% 伤害。' },
      3: { damage: 0.1, description: '增加 10% 伤害。' },
      4: { damage: 0.1, description: '增加 10% 伤害。' },
      5: { damage: 0.1, description: '增加 10% 伤害。' },
    },
  },
  armor: {
    id: 'armor',
    name: '龟壳',
    description: '减少 1 点受到的伤害。',
    maxLevel: 5,
    color: '#aaaaaa',
    statModifiers: {
      1: { armor: 1, description: '减少 1 点受到的伤害。' },
      2: { armor: 1, description: '减少 1 点受到的伤害。' },
      3: { armor: 1, description: '减少 1 点受到的伤害。' },
      4: { armor: 1, description: '减少 1 点受到的伤害。' },
      5: { armor: 1, description: '减少 1 点受到的伤害。' },
    },
  },
  boots: {
    id: 'boots',
    name: '天狗木屐',
    description: '增加 10% 移动速度。',
    maxLevel: 5,
    color: '#55ff55',
    statModifiers: {
      1: { speed: 0.1, description: '增加 10% 移动速度。' },
      2: { speed: 0.1, description: '增加 10% 移动速度。' },
      3: { speed: 0.1, description: '增加 10% 移动速度。' },
      4: { speed: 0.1, description: '增加 10% 移动速度。' },
      5: { speed: 0.1, description: '增加 10% 移动速度。' },
    },
  },
  tome: {
    id: 'tome',
    name: '魔导书',
    description: '减少 8% 武器冷却时间。',
    maxLevel: 5,
    color: '#5555ff',
    statModifiers: {
      1: { cooldown: -0.08, description: '减少 8% 武器冷却时间。' },
      2: { cooldown: -0.08, description: '减少 8% 武器冷却时间。' },
      3: { cooldown: -0.08, description: '减少 8% 武器冷却时间。' },
      4: { cooldown: -0.08, description: '减少 8% 武器冷却时间。' },
      5: { cooldown: -0.08, description: '减少 8% 武器冷却时间。' },
    },
  },
  orb: {
    id: 'orb',
    name: '阴阳玉',
    description: '增加 25% 拾取范围。',
    maxLevel: 5,
    color: '#ff00ff',
    statModifiers: {
      1: { magnet: 0.25, description: '增加 25% 拾取范围。' },
      2: { magnet: 0.25, description: '增加 25% 拾取范围。' },
      3: { magnet: 0.25, description: '增加 25% 拾取范围。' },
      4: { magnet: 0.25, description: '增加 25% 拾取范围。' },
      5: { magnet: 0.25, description: '增加 25% 拾取范围。' },
    },
  },
  clover: {
    id: 'clover',
    name: '四叶草',
    description: '增加 10% 幸运（影响掉落率）。',
    maxLevel: 5,
    color: '#00ff00',
    statModifiers: {
      1: { luck: 0.1, description: '增加 10% 幸运。' },
      2: { luck: 0.1, description: '增加 10% 幸运。' },
      3: { luck: 0.1, description: '增加 10% 幸运。' },
      4: { luck: 0.1, description: '增加 10% 幸运。' },
      5: { luck: 0.1, description: '增加 10% 幸运。' },
    },
  },
  crown: {
    id: 'crown',
    name: '皇冠',
    description: '增加 8% 经验获取量。',
    maxLevel: 5,
    color: '#ffff00',
    statModifiers: {
      1: { expMultiplier: 0.08, description: '增加 8% 经验获取量。' },
      2: { expMultiplier: 0.08, description: '增加 8% 经验获取量。' },
      3: { expMultiplier: 0.08, description: '增加 8% 经验获取量。' },
      4: { expMultiplier: 0.08, description: '增加 8% 经验获取量。' },
      5: { expMultiplier: 0.08, description: '增加 8% 经验获取量。' },
    },
  },
  fang: {
    id: 'fang',
    name: '吸血鬼之牙',
    description: '攻击时有 1% 几率恢复 1 点生命值。',
    maxLevel: 5,
    color: '#aa0000',
    statModifiers: {
      1: { lifesteal: 0.01, description: '增加 1% 吸血几率。' },
      2: { lifesteal: 0.01, description: '增加 1% 吸血几率。' },
      3: { lifesteal: 0.01, description: '增加 1% 吸血几率。' },
      4: { lifesteal: 0.01, description: '增加 1% 吸血几率。' },
      5: { lifesteal: 0.01, description: '增加 1% 吸血几率。' },
    },
  },
};

export const UPGRADES: Upgrade[] = [
  {
    id: 'damage',
    name: '力量',
    description: '每级增加 5% 基础伤害。',
    maxLevel: 5,
    baseCost: 200,
    costMultiplier: 1.5,
    statIncrease: 0.05,
  },
  {
    id: 'maxHp',
    name: '最大生命值',
    description: '每级增加 10% 最大生命值。',
    maxLevel: 5,
    baseCost: 200,
    costMultiplier: 1.5,
    statIncrease: 0.1,
  },
  {
    id: 'armor',
    name: '护甲',
    description: '每级减少 1 点受到的伤害。',
    maxLevel: 3,
    baseCost: 300,
    costMultiplier: 2,
    statIncrease: 1,
  },
  {
    id: 'speed',
    name: '移动速度',
    description: '每级增加 5% 移动速度。',
    maxLevel: 5,
    baseCost: 200,
    costMultiplier: 1.5,
    statIncrease: 0.05,
  },
  {
    id: 'magnet',
    name: '拾取范围',
    description: '每级增加 10% 拾取范围。',
    maxLevel: 5,
    baseCost: 200,
    costMultiplier: 1.5,
    statIncrease: 0.1,
  },
  {
    id: 'cooldown',
    name: '冷却缩减',
    description: '每级减少 2.5% 武器冷却时间。',
    maxLevel: 4,
    baseCost: 400,
    costMultiplier: 2,
    statIncrease: -0.025,
  },
  {
    id: 'amount',
    name: '投射物数量',
    description: '所有武器发射 1 个额外的投射物。',
    maxLevel: 1,
    baseCost: 5000,
    costMultiplier: 1,
    statIncrease: 1,
  },
];
